apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-backup-controller
  namespace: system
  labels:
    control-plane: image-backup-controller
spec:
  selector:
    matchLabels:
      control-plane: image-backup-controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: image-backup-controller
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-backup-ctrl-sa
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-backup-ctrl-cr
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets"]
    verbs: ["get", "watch", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-backup-ctrl-cb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-backup-ctrl-cr
subjects:
  - kind: ServiceAccount
    name: image-backup-ctrl-sa
    namespace: system